19:32:54.390 INFO Test execution started: login.login
19:32:54.390 INFO Browser: chrome
19:32:54.391 INFO Test started: test
19:32:54.391 INFO Navigate to: 'https://staging.nalarocks.com/'
19:33:17.100 ERROR ElementNotFound: Element data-testid="input-text-controller" not found using selector css:'data-testid="input-text-controller"'
Traceback (most recent call last):
  File "/home/lautaro/env/lib/python3.10/site-packages/golem/test_runner/test_runner.py", line 202, in run_test_function
    f(execution.data)
  File "/home/lautaro/test_directory/projects/nala/tests/login/login.py", line 6, in test
    send_keys(('data-testid="input-text-controller"'), 'nala@nalarocks.com')
  File "/home/lautaro/env/lib/python3.10/site-packages/golem/actions.py", line 1576, in send_keys
    element = get_browser().find(element)
  File "/home/lautaro/env/lib/python3.10/site-packages/golem/webdriver/extended_driver.py", line 177, in find
    return common._find(self, element, id, name, link_text, partial_link_text, css,
  File "/home/lautaro/env/lib/python3.10/site-packages/golem/webdriver/common.py", line 130, in _find
    webelement = _find_webelement(self, selector_type, selector_value, element_name,
  File "/home/lautaro/env/lib/python3.10/site-packages/golem/webdriver/common.py", line 46, in _find_webelement
    raise ElementNotFound('Element {0} not found using selector {1}:\'{2}\''
golem.core.exceptions.ElementNotFound: Element data-testid="input-text-controller" not found using selector css:'data-testid="input-text-controller"'
19:33:17.109 WARNING There was an error while taking screenshot:
Traceback (most recent call last):
  File "/home/lautaro/env/lib/python3.10/site-packages/golem/test_runner/test_runner.py", line 202, in run_test_function
    f(execution.data)
  File "/home/lautaro/test_directory/projects/nala/tests/login/login.py", line 6, in test
    send_keys(('data-testid="input-text-controller"'), 'nala@nalarocks.com')
  File "/home/lautaro/env/lib/python3.10/site-packages/golem/actions.py", line 1576, in send_keys
    element = get_browser().find(element)
  File "/home/lautaro/env/lib/python3.10/site-packages/golem/webdriver/extended_driver.py", line 177, in find
    return common._find(self, element, id, name, link_text, partial_link_text, css,
  File "/home/lautaro/env/lib/python3.10/site-packages/golem/webdriver/common.py", line 130, in _find
    webelement = _find_webelement(self, selector_type, selector_value, element_name,
  File "/home/lautaro/env/lib/python3.10/site-packages/golem/webdriver/common.py", line 46, in _find_webelement
    raise ElementNotFound('Element {0} not found using selector {1}:\'{2}\''
golem.core.exceptions.ElementNotFound: Element data-testid="input-text-controller" not found using selector css:'data-testid="input-text-controller"'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lautaro/env/lib/python3.10/site-packages/golem/actions.py", line 154, in _screenshot_on_condition
    screenshot_filename = _capture_screenshot(screenshot_name)
  File "/home/lautaro/env/lib/python3.10/site-packages/golem/actions.py", line 96, in _capture_screenshot
    get_browser().get_screenshot_as_file(screenshot_path)
  File "/home/lautaro/env/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 1032, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "/home/lautaro/env/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 1064, in get_screenshot_as_png
    return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "/home/lautaro/env/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 1074, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "/home/lautaro/env/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/lautaro/env/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=104.0.5112.101)


19:33:17.109 INFO Test Result: CODE ERROR
